### ISSUE TITLE
Add hactoberfest label and Hactoberfest accepted topic

### ISSUE THREAD

**Issue by sudhanshutiwari264** [OpenSouceCode/Hacktoberfest2020#1457]

**Comment by HammedBabatunde** [comment]
Hello please can you assign this issue to me

**Comment by sudhanshutiwari264** [comment]
@HammedBabatunde  I m not among the maintainers and I am not the owner only owner can add hactoberfest-accepted label and Hactoberfest topic to the repo

**Comment by sudhanshutiwari264** [comment]
@HammedBabatunde  check the pinned issue !
