### ISSUE TITLE
Ineligible repository

### ISSUE THREAD

**Issue by csymvoul** [OpenSouceCode/Hacktoberfest2020#2048]
I did the PR and even though it got accepted: https://github.com/OpenSouceCode/Hacktoberfest2020/pull/2046 on the hacktoberfest site it notes it as ineligible. 
You may see the result in the figure below: 

![image](https://user-images.githubusercontent.com/36190914/95325914-81330880-08aa-11eb-84d1-aa5e4d2928fc.png)

**Comment by adreaskar** [comment]
Same here. Found this #302
