### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by IrfanNawawi** [OpenSouceCode/Hacktoberfest2020#312]
I am a newbie, please add in readme.md the user guide how to solve failed deployments, thanks

Preparing Git Reference pull/311/head
7:04:00 PM: Error checking out submodules: fatal: No url found for submodule path 'Hacktoberfest2020' in .gitmodules
7:04:00 PM: Failing build: Failed to prepare repo
7:04:00 PM: Failed during stage 'preparing repo': Error checking out submodules: fatal: No url found for submodule path 'Hacktoberfest2020' in .gitmodules

**Comment by aryasoni98** [comment]
Read the README.md file Proper Guide for beginner
