### ISSUE TITLE
Wanna know when to make a pull request

### ISSUE THREAD

**Issue by HarshAgarwal-DEV** [OpenSouceCode/Hacktoberfest2020#59]
as after studying on official website i got to know that all contributions are counted from month of october so we have to pull request in month of october or september only

**Comment by aryasoni98** [comment]
Yes , 
Pull Request counted on Hacktoberfest Oct.

**Comment by Sumitlovanshi** [comment]
In the month of october only

**Comment by trivediavinash** [comment]
Will i get a t-shirt for successfully merged pull request

**Comment by crpoudyal** [comment]
I think the main objectives of everyone should be about your first PR, not any t-shirt...what you guys will say let me know your thoughts...

**Comment by rohan2734** [comment]
ya , but where are the projects , for which we can contribute, do you add any labels to the PRs?, how do you count the contributions?

**Comment by mrityunjay2627** [comment]
I seriously wanna contribute to open source. I am learning HTML/CSS by making a project.

**Comment by geeks5551** [comment]
hey can I contribute  to this  issue ? looking interesting?
